### ISSUE TITLE
`hover` doesn't use input column names

### ISSUE THREAD

**Issue by kthyng** [holoviz/hvplot#1356]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```
jupyter                   1.0.0 
hvplot                    0.10.0  
bokeh                     3.4.1 
holoviews                 1.18.3   
Python 3.12.0 
```

#### Description of expected behavior and the observed behavior

I would like to have alternative column values displayed with hover, but the hover always shows the x and y values instead and only those. I can get it to respect the boolean `False` instead, so it seems to be interpreting my list as `True`.

#### Complete, minimal, self-contained example code that reproduces the issue

example file: 
[test.tsv.zip](https://github.com/user-attachments/files/15890470/test.tsv.zip)

```
import hvplot.pandas
import pandas as pd

# skipping bottom depth, sigma, press
csv_kwargs = dict(encoding = "ISO-8859-1", sep="\t",
                 dtype={"Station": str, 'mon/day/yr': str, 'hh:mm': str})
hover_cols = ["Lon", "Lat"]

df = pd.read_csv("~/Downloads/test.tsv", **csv_kwargs)

df.hvplot(**{'kind': 'line',
 'y': ['Temperature [C]', 'Salinity [psu]'],
 'x': "Depth [m]",
 'invert': True,
 'flip_yaxis': True,
 'subplots': True,
 'shared_axes': False,
 'hover': hover_cols,
})

```

Thanks!

**Comment by droumis** [comment]
I think you're looking for the `hover_cols` arg in order to add cols to the tooltips.

![image](https://github.com/holoviz/hvplot/assets/6613202/8059e51c-7cee-41d6-aa92-1519bbd9f862)


In order to replace the x and y and fully specify the tooltip, in the new HoloViews release (1.19.0) you can use the new `hover_tooltips` arg applied to the underlying Curve elements to limit the hover tooltip columns:

![image](https://github.com/holoviz/hvplot/assets/6613202/5da57bda-82f9-4fc1-b83e-f987b94ba7c6)

**Comment by kthyng** [comment]
Duh! I am sorry for this extraneous issue! This explains my confusion... I had it working and then it mysteriously stopped working. I must have changed the keyword I was using in my code. 😆

**Comment by maximlt** [comment]
> I think incorporating the new `hover_tooltips` functionality into hvPlot, probably replacing the existing `hover_cols`, might be a reasonable enhancement target. @maximlt, any thoughts?

Yes good idea! https://github.com/holoviz/hvplot/issues/1357
