### ISSUE TITLE
Support switching plotting backends in hvPlot

### ISSUE THREAD

**Issue by mfouesneau** [holoviz/hvplot#156]
HV allows one to use other renderer, for instance matplotlib. How do one can setup matplotlib with hvplot?

**Comment by ahuang11** [comment]
Same way.

import hvplot.xarray
import holoviews as hv
hv.extension('matplotlib')

**Comment by jbednar** [comment]
I don't think hvplot has been tested much using the matplotlib backend.  So it's not explicitly forbidden, but some plot types are not likely to be full supported.  I'd be happy to accept a PR addressing any issues from someone who goes through each of the plot types in turn and tries them out.  But it's not something we're likely to do ourselves in the near future otherwise.

**Comment by philippjfr** [comment]
Yeah, hvplot was written mainly with the bokeh backend in mind. I don't think it would be a huge amount of effort but in the current state it is not really supported in any real sense.

**Comment by mfouesneau** [comment]
The renderer is hardcoded but I cannot find where to change it. In utilities.py it's not applied

**Comment by waooga** [comment]
Has there been any movement on this? I am trying to run hvplot.save() and keep getting a 'Remote end closed connection without response' error. I have set dynamic=False, but since I am only trying to save a static png I thought changing the backend to Matplotlib might fix my issue.

**Comment by philippjfr** [comment]
There are now issues specific to Matplotlib (#243) and Plotly (#480) support so I'll close this as a duplicate.
