### ISSUE TITLE
Hover on Graph does not correctly use the index_hover column

### ISSUE THREAD

**Issue by philippjfr** [holoviz/hvplot#189]
When declaring a Graph plot it seems the hover tool references the ``index`` column not the ``index_hover`` column which means the internal numeric indexes rather than the user supplied values are displayed. Currently you can work around this with:

```python
from bokeh.models import HoverTool

GG = nx.Graph()
GG.add_edge('A','B')
GG.add_edge('B','C')
GG.add_edge('C','A')
hvnx.draw(GG).opts(tools=[HoverTool(tooltips=[('index', '@index_hover')])])
```

**Comment by ehudkr** [comment]
On the risk of being obvious, I'd like to mention that this problem exists also in edge-centric hover when `inspection_policy=edges`. 
Since finding the workaround for this case took me down the rabbit hole of the figure objects, I thought it would be better shared in case others encounter it as well.

**Reproducible example:**
```python
import networkx as nx
import hvplot.networkx as hvnx
from bokeh.models import HoverTool

GG = nx.Graph()
GG.add_edge('A', 'B')
GG.add_edge('B', 'C')
GG.add_edge('C', 'A')
GG = hvnx.draw(GG, inspection_policy="edges")
hvnx.show(GG)
```
Outputs:
![image](https://user-images.githubusercontent.com/15989012/63534086-fad92d00-c516-11e9-8ec4-62db70cd9924.png)


In which case the workaround needed is:
(note the `_values` suffix, instead the `_hover` as above)
```python
GG.opts(tools=[HoverTool(tooltips=[('start', '@start_values'),
                                   ('end', '@end_values')])])
hvnx.show(GG)
```

Outputs:
![image](https://user-images.githubusercontent.com/15989012/63534162-2fe57f80-c517-11e9-817a-ff30e7b7d910.png)
