### ISSUE TITLE
Please support pylint

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#413]
#### My Pain

I use hvplot and pylint. But they don't work well together.

If I have a line of code like `data.hvplot...` then I get the error 

```bash
E1101: Instance of 'DataFrame' has no 'hvplot' member (no-member)
```

from pylint.

#### Solution

I don't know how to solve this technically. But it would be very nice to have a solution.

**Comment by jbednar** [comment]
Pylint's messages can easily be controlled: http://pylint.pycqa.org/en/latest/user_guide/message-control.html

I think you can also avoid the warning by using `.plot()` instead of `.hvplot()`, as long as you configure the new Pandas plotting entrypoint support with `import hvplot ; pandas.set_option("plotting.backend", "holoviews")`.  @philippjfr may have done this automatically somewhere as well; not sure.

**Comment by MarcSkovMadsen** [comment]
Suggestion 1 with Pylint messages is not really a solution. It's a workaround and the workaround I currently use. I have to insert the line `# pylint: disable=no-member` for every use of `.hvplot` in my code.

Suggestion 2 I will try out. But we are using a mix of holoviews, plotly and altair in our code so it might not be the best option to specify.

**Comment by philippjfr** [comment]
I don't think this is something that can be solved in hvPlot. hvPlot either monkey-patches the attribute and/or using existing mechanisms to add an accessor, if pylint doesn't have nice ways to handle these situations there is very little we can do.

**Comment by jbednar** [comment]
The discussion here may have some ideas that could work: https://stackoverflow.com/questions/33961756/disabling-pylint-no-member-e1101-error-for-specific-libraries
