### ISSUE TITLE
Contours rather than filled contours shown when using datashader

### ISSUE THREAD

**Issue by jchutrue** [holoviz/hvplot#417]
There is a difference in the behavior of the contourf() method when I use datashader and when I don't. Below is the code I used:

```python
contourf1 = xa.hvplot.contourf(levels=30, aggregator=ds.max(xa.name), 
                          cmap=plt.cm.magma, colorbar=True, hover=True, ylim=[1, 50])
contourf2 = xa.hvplot.contourf(levels=30, aggregator=ds.max(xa.name), 
                          cmap=plt.cm.magma, colorbar=True, hover=True, ylim=[1, 50], rasterize=True)
(contourf1 + contourf2).cols(1)
```
And the output is the following:
![Selection_281](https://user-images.githubusercontent.com/14321886/75057828-748aad00-549f-11ea-9a1e-a582dade2c48.png)

When I used the hover tool, the white regions of the second plot said Z=-NaN. However, I verified that all the data were finite and not NaN's. Secondly when I zoomed into the second plot, I saw that the contours were actually not being filled, so it's behaving more like a contour rather than contourf plot.

**Comment by jbednar** [comment]
Thanks for the bug report! There are various issues involved here:  

- [ ] First, hvPlot should presumably be erroring or warning for `.contourf` combined with `rasterize=True`. Even though hvPlot supports `rasterize` and `contourf` separately (which is why there is currently no error message), the combination of those two is not currently supported because at the time that code was written Datashader had no ability to fill between contours.  At a minimum, the absence of such an error message is a bug.
- [ ] More usefully, HoloViews should now be updated to support datashading filled contours, which should be feasible given the polygon-with-holes support added to Datashader a couple of months ago. The actual code for this shouldn't be difficult, but the HoloViews API will be tricky, because in HoloViews filled and unfilled contourse are the same Element, with filling determined only by a HoloViews option, and those options are not currently passed down to the Datashader call.  Probably we'll need a new specialized rasterizing call for contours, and then people who want to rasterize filled contours will have to pass that argument in to the new specialized rasterize operation.
- [ ] Once HoloViews supports rasterizing filled contours, it should be trivial to update hvPlot's contourf to pass the correct argument when `contourf` is used with `rasterize=True`.
- [ ] The NaN values should then automatically disappear.  Right now you're getting NaNs because the contours are not filled, which means that the output pixel array has data overlapping only some of the pixels. Datashader uses NaN to indicate any pixel that had no data in it, which should apply to most of the pixels in the case where only discrete contours being drawn. Once contours are filled, all pixels should have data, and so you should no longer get NaNs. In any case the NaNs in the rasterized array are fully independent of the contents of the input data; for rasterized output they simply report the presence of data for that pixel, which is separate from whether the non-rasterized data has NaNs in it.

If you do want to use unfilled contours (all that's currently supported for datashading), then you should make sure that the background color visible for NaN values is appropriate for your chosen colormap. Here, you would use something like `contourf2.opts(bgcolor='black')`.

Hope this helps, and thanks again for letting us know about the issue!

**Comment by jbednar** [comment]
Oh, and btw, is there some reason you want to use filled contours here in the first place?  If I wanted to plot data like that with Datashader I would just do `xa.hvplot(aggregator=ds.max(xa.name), cmap=plt.cm.magma, colorbar=True, hover=True, ylim=[1, 50])`; filling contours seems more important when not using Datashader so that you can approximate arbitrarily dense data with a feasible equivalent, while Datashader should make _any_ size of data feasible to plot directly.

**Comment by jchutrue** [comment]
@jbednar Thanks for the response! The problem is that the y-axis values are not regularly spaced, so I get a warning from using a bare hvplot (and the output doesn't look right):

![Selection_283](https://user-images.githubusercontent.com/14321886/75067219-2af78d80-54b2-11ea-8c4d-4d5178962d8e.png)

Typically I use a quadmesh. For lack of a better word, it looks pixelated:
![Selection_282](https://user-images.githubusercontent.com/14321886/75066632-d6074780-54b0-11ea-9fd4-f681237e0bc7.png)

This is exactly what I expect because the data were generated from a sampled version of a transform defined for continuous signals.

However, I am developing a library for users who expect to see something a little "smoother" than the quadmesh output, along with interactivity. Using hvplot's contourf without rasterizing ends up being very slow to zoom in and slower to render as well. And then exporting to svg (since vectorized graphics for scientific publication is preferred) by using the bokeh renderer is also orders of magnitude slower.

**Comment by jbednar** [comment]
Ah. That's a bit of a mess. Yes, quadmesh is needed if the spacing isn't constant, but in Datashader, I think only rasters currently support interpolating between grid cell values; quadmeshes were implemented independently of rasters and have no interpolation like that. Calculating such interpolation is a bit tricky when the spacing is irregular, but would be great to have someone work on.  So I don't think there's currently a Datashader-based solution for your use case.  Datashader would work fine if you had a much denser quadmesh, though!

**Comment by jchutrue** [comment]
Right, increasing the density can easily be done. The separate issue is that a lot of memory can be consumed if people are working with long timeseries (think 2-4 hours of data sampled at 1 kHz), so most of the time they use a spacing of 10-16 frequencies per octave. 

Using a linear scale the spacing is iregular but on a log scale, it is constant. I wonder if there is a way to interpolate in the log domain and then map into linear?

**Comment by jbednar** [comment]
Right; I just meant that Datashader is meant for the case where you are trying to visualize data already densely sampled.  It _could_ be extended to support this case as well by doing interpolation on quadmeshes, but usually it's used for the opposite problem (data too densely sampled to view easily). 

In any case yes, you should be able to use a raster if you specify logy=True, which might help since a raster can support interpolation.  I don't know if hvPlot exposes Datashader's interpolation options anywhere, but if logy does make it work with a raster in this case, then exposing the interpolation options shouldn't be difficult at all.

**Comment by philippjfr** [comment]
Fixed with latest HoloViews.
