### ISSUE TITLE
Tiles image is not projected if projection is not mercator

### ISSUE THREAD

**Issue by MordicusEtCubitus** [holoviz/hvplot#529]
Hi,
First of all I would like to thanks you a lot for the great work done with HvPlot and the Holoviz ecosystem: plotting huge data with bokeh, cartopy and data shader has never been so easy.

I've tried to plot a big dataframe having 50 millions  of records this way:

**df** is the dataframe

```python
import hvplot.pandas
from cartopy import crs
proj = crs.Robinson() # crs.GOOGLE_MERCATOR  # crs.Mercator()
df.hvplot.points(x='LONGITUDE', y='LATITUDE', geo=True, projection=proj, c='Value'
                 , datashade=True
                 , aggregator=ds.mean('Value')
                 , tiles='ESRI'
                 , coastline=True
                 , project=True
                )
```
The data and coastlines are correctly projected, but not the background image, as you can see in the attached picture.
Is this a bug or did I missed something ?
Thanks a lot for helping !
```pyhton
import cartopy
print(hvplot.__version__)
print(cartopy.__version__)

0.6.0
0.18.0
```
![robinson_hvplot](https://user-images.githubusercontent.com/562142/100395885-07fe9900-3043-11eb-80ef-48764e8df734.png)

**Comment by jbednar** [comment]
I would have expected at least a warning in that case, if not an error, because tiles only support a Web Mercator projection.  I would have hoped that everything gets forced into Web Mercator, with a warning saying that the `projection` is being ignored, or else an error saying that tiles cannot be overlaid because the projection is not Web Mercator.

**Comment by jsignell** [comment]
I will include this in my PR tackling #951 and #738
