### ISSUE TITLE
pyproj is required for coastline, but doesn't say in error message

### ISSUE THREAD

**Issue by ahuang11** [holoviz/hvplot#534]
```
~/anaconda3/envs/py3/lib/python3.8/site-packages/hvplot/util.py in process_crs(crs)
    182         import pyproj
    183     except:
--> 184         raise ImportError('Geographic projection support requires GeoViews and cartopy.')
    185 
    186     if crs is None:

ImportError: Geographic projection support requires GeoViews and cartopy.
```
Only specifies GeoViews and cartopy, but not pyproj.

**Comment by jbednar** [comment]
Isn't pyproj already a dependency of cartopy? At least in conda, pyproj automatically gets installed with cartopy (see output of `conda create --dry-run -n d cartopy`). And since cartopy is a direct dependency of geoviews, seems like this message can simply say that projection support requires GeoViews.
