### ISSUE TITLE
clim not findable 

### ISSUE THREAD

**Issue by robfatland** [holoviz/hvplot#559]
Documentation: I needed to stipulate a fixed color range for `hvplot.image()` but could not find the keyword `clim=(a, b)`.  

Am I missing it somewhere? tx

**Comment by dhruvbalwada** [comment]
It does seem like clim has not been exposed with `hvplot.image()`. You can find the exposed options by running `hvplot.help('image')`. 

Since `hvplot.image()` creates a holoviews `Image` element underneath, you can style it using the options available with holoviews. One way to do this would look like `hvplot.image().opts(clim=(-10,10))`. The guide is here: http://holoviews.org/user_guide/Applying_Customizations.html
