### ISSUE TITLE
The Interactive.ipynb does not seem to work

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [holoviz/hvplot#664]
I downloaded the Interactive.ipynb and quickly went through the tutorial. The widgets were rendered successfully but plots did not update when I changed the values on these widgets.

**Comment by bmwilly** [comment]
fwiw, I am seeing the same behavior with recently installed packages: 

```
$ conda list "bokeh|holoviews|panel|hvplot"
# packages in environment at /Users/bwilliams/miniforge3/envs/test:
#
# Name                    Version                   Build  Channel
bokeh                     2.3.3            py39h2804cbe_0    conda-forge
holoviews                 1.14.6             pyhd8ed1ab_0    conda-forge
hvplot                    0.7.3              pyh6c4a22f_0    conda-forge
panel                     0.12.1             pyhd8ed1ab_0    conda-forge
```

**Comment by jbednar** [comment]
FWIW, I tried that notebook with bokeh=2.4.1, holoviews=1.14.7, hvplot=0.7.3, and panel=0.12.4 running cell by cell, and found:

- cell 3 (`ds.air.interactive(width=800).isel(time=slider)`) worked fine (updating the DataArray repr as I dragged the slider)
- cell 4 (same as 3 but with ipw.IntSlider) did not update the repr
- cell 5 gives a `KeyError: 1356998400000000000`
- cell 6 works (printing a docstring)
- cell 7 gives a `KeyError: 1356998400000000000`
- cell 8 works playing a loop of Matplotlib plots, but also shows a blank Matplotlib plot after the player: 
![image](https://user-images.githubusercontent.com/1695496/148615415-6f1e89e6-9ba8-4198-a16a-aeb46a8a2891.png)

- cell 9 works
- cell 10 gives a `KeyError: 1356998400000000000`
- cell 11 works
- cell 12 works
- cell 13 works
- cell 14 works, but it now wraps the number onto a newline that makes it look like there are two numbers output: 
![image](https://user-images.githubusercontent.com/1695496/148615494-b6e8eaa7-4199-4c2c-8ff5-d6cc7b66585e.png)

- cell 15 works, but it now wraps the number onto a newline that makes it look like there are two numbers output
- cell 16 gives a `KeyError: 1356998400000000000`
- cell 17 gives a `KeyError: 1356998400000000000`

I get the same results with hvplot master (hvplot=0.8.0a10.post1+g25f3285). The problem with cells 14 and 15 seems minor (though confusing!), but the rest seem serious.

**Comment by droumis** [comment]
All the cells now work for me except cell 5, which does not update with the slider, and I receive the following warning: 

`WARNING:param.ParamFunction01126: The function 'evaluate' does not have any dependencies and will never update. Are you sure you did not intend to depend on or bind a parameter or widget to this function? If not simply call the function before passing it to Panel. Otherwise, when passing a parameter as an argument, ensure you pass at least one parameter and reference the actual parameter object not the current value, i.e. use object.param.parameter not object.parameter.
`

bokeh: 2.4.3
holoviews: 1.15.0
hvplot: 0.8.1a1.post22+gb49006f
panel: '0.13.1'
param: '1.12.2'

**Comment by maximlt** [comment]
@droumis could you open a new issue with a reproducible example? I'm afraid it'll get lost in this one.

**Comment by droumis** [comment]
I can no longer reproduce this issue
